TR029 wrtite Barrier factor
ComPWA/report pull request #25
Opened 2024-11-08 13:53 UTC by shenvitor

- Closes #15

2024-11-08 14:17 UTC, redeboer requested changes

2024-11-08 14:17 UTC, redeboer commented on docs/029/index.ipynb
> +     "source_hidden": true
Could you unhide this cell again?

2024-11-12 13:41 UTC, shenvitor commented on docs/029/index.ipynb
> +     "source_hidden": true
done

2025-01-13 19:22 UTC, redeboer approved these changes
🦘

2025-01-13 19:26 UTC, merged